-- MySQL Script generated by MySQL Workbench
-- Tue Oct 23 21:24:12 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;

-- -----------------------------------------------------
-- Table `project`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`province` (
  `province_id` VARCHAR(5) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `type` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`province_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `project`.`district`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`district` (
  `district_id` VARCHAR(5) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `type` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `province_id` VARCHAR(5) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`district_id`, `province_id`),
  INDEX `fk_district_province1_idx` (`province_id` ASC) VISIBLE,
  CONSTRAINT `fk_district_province1`
    FOREIGN KEY (`province_id`)
    REFERENCES `project`.`province` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `project`.`commune`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`commune` (
  `commune_id` VARCHAR(5) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `type` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `district_id` VARCHAR(5) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`commune_id`, `district_id`),
  INDEX `fk_commune_district_idx` (`district_id` ASC) VISIBLE,
  CONSTRAINT `fk_commune_district`
    FOREIGN KEY (`district_id`)
    REFERENCES `project`.`district` (`district_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `project` ;

-- -----------------------------------------------------
-- Table `project`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `project`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`photo` (
  `photo_id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(256) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`photo_id`, `post_id`, `user_id`),
  INDEX `fk_photo_post1_idx` (`post_id` ASC) VISIBLE,
  INDEX `fk_photo_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_photo_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_photo_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`post` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `commune_id` VARCHAR(5) CHARACTER SET 'utf8' NOT NULL,
  `category_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  `remuneration` DOUBLE NOT NULL,
  `location_coordinate` VARCHAR(128) NULL,
  `title` VARCHAR(4096) NOT NULL,
  `content` VARCHAR(4096) NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`post_id`, `commune_id`, `category_id`, `user_id`),
  INDEX `fk_post_commune_idx` (`commune_id` ASC) VISIBLE,
  INDEX `fk_post_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_post_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_commune`
    FOREIGN KEY (`commune_id`)
    REFERENCES `project`.`commune` (`commune_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(256) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(256) NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
